import { Fighter, Facility, MarketingCampaign, Venue } from './types';

export const INITIAL_MONEY = 0;
export const INITIAL_POPULARITY = 1;

/**
 * Mean match score fans expect at each whole promotion popularity tier (index 0 = tier 1 → 80).
 * Higher tiers reuse the last value (cap).
 */
export const EXPECTED_AVERAGE_MATCH_SCORE_BY_POPULARITY_TIER: readonly number[] = [
  80, 95, 110, 125, 140, 155, 170, 185, 200, 215, 230, 245, 260, 275, 290, 305, 320, 335, 350, 365, 380,
  395,
];

export function expectedAverageMatchScoreForPopularityTier(tier: number): number {
  const t = Math.max(1, Math.floor(tier));
  const table = EXPECTED_AVERAGE_MATCH_SCORE_BY_POPULARITY_TIER;
  return table[Math.min(t - 1, table.length - 1)];
}

/** Multiplier applied to `GameState.popularity` when ending a day with no card booked. */
export const NO_SHOW_DAY_POPULARITY_FACTOR = 0.9;

/** Buzz multiplier when the match includes at least one fighter on their first match (`Fighter.debutMatchPending`, see `matchScoring`). */
export const DEBUT_MATCH_MULTIPLIER = 1.5;

export const VENUES: Venue[] = [
  {
    id: 'backyard',
    name: 'Backyard',
    cost: 0,
    multiplier: 1,
    minPopularity: 0,
    maxAudience: 75,
    baseTicketPrice: 10,
  },
  {
    id: 'gym',
    name: 'High School Gym',
    cost: 500,
    multiplier: 1.5,
    minPopularity: 5,
    maxAudience: 420,
    baseTicketPrice: 16,
  },
  {
    id: 'club',
    name: 'Nightclub',
    cost: 1500,
    multiplier: 2.5,
    minPopularity: 15,
    maxAudience: 1100,
    baseTicketPrice: 26,
  },
  {
    id: 'arena',
    name: 'City Arena',
    cost: 5000,
    multiplier: 5,
    minPopularity: 40,
    maxAudience: 5200,
    baseTicketPrice: 42,
  },
];

export const STARTING_FIGHTERS: Fighter[] = [
  {
    id: 'f1',
    name: 'The Iron Giant',
    stats: { power: 28, mic: 14, endurance: 20, technique: 16 },
    salary: 0,
    signingBonus: 0,
    popularity: 6,
    energy: 100,
    alignment: 'Heel',
    trait: 'Powerhouse',
    injuryDays: 0,
    recoveringFromInjury: false,
    image: '/wrestler.png',
  },
  {
    id: 'f2',
    name: 'Neon Ninja',
    stats: { power: 14, mic: 22, endurance: 22, technique: 26 },
    salary: 0,
    signingBonus: 0,
    popularity: 8,
    energy: 100,
    alignment: 'Face',
    trait: 'High Flyer',
    injuryDays: 0,
    recoveringFromInjury: false,
    image: '/wrestler.png',
  },
  {
    id: 'f3',
    name: 'Bulk Hogan',
    stats: { power: 26, mic: 20, endurance: 16, technique: 14 },
    salary: 0,
    signingBonus: 0,
    popularity: 10,
    energy: 100,
    alignment: 'Face',
    trait: 'Brawler',
    injuryDays: 0,
    recoveringFromInjury: false,
    image: '/wrestler.png',
  },
];

/** Max facility `level` per `GameState.leagueIndex` (aligned with `LEAGUE_TIERS` order). */
const FACILITY_MAX_LEVEL_BY_LEAGUE = {
  /** Performance Center level = concurrent training slots; starts at 0 (no camp until upgraded). */
  performance_center: [1, 2, 3, 4],
  /** First league: 3; second: 5; then +2 per promotion (example curve). */
  wellness_center: [3, 5, 7, 9],
  merch_booth: [4, 6, 8, 10],
  travel_package: [3, 5, 7, 10],
  sponsor_lounge: [3, 5, 8, 12],
} as const satisfies Record<string, readonly number[]>;

export const AVAILABLE_FACILITIES: Facility[] = [
  {
    id: 'performance_center',
    name: 'Performance Center',
    level: 0,
    baseCost: 4200,
    upgradeCostMultiplier: 2.1,
    maxLevelByLeagueIndex: [...FACILITY_MAX_LEVEL_BY_LEAGUE.performance_center],
    description:
      'Each level is one concurrent rookie camp slot. At level 0 you cannot run camp—upgrade here, or sign prospects raw (weaker, no slot).',
    effect: '+1 recruit training slot per level (0 = none)',
  },
  {
    id: 'wellness_center',
    name: 'Wellness Center',
    level: 0,
    baseCost: 2_800,
    upgradeCostMultiplier: 2.65,
    firstUpgradeDiscount: 500,
    maxLevelByLeagueIndex: [...FACILITY_MAX_LEVEL_BY_LEAGUE.wellness_center],
    description: 'Sports science, sleep tracking, and soft-tissue work so the roster bounces back faster between cards.',
    effect: '+1 daily energy recovery per fighter per level',
  },
  {
    id: 'merch_booth',
    name: 'Merch Booth',
    level: 0,
    baseCost: 3_200,
    upgradeCostMultiplier: 2.25,
    requiredLeagueIndex: 1,
    maxLevelByLeagueIndex: [...FACILITY_MAX_LEVEL_BY_LEAGUE.merch_booth],
    description: 'Move branded gear on the road; fans leave with shirts and you leave with extra gate.',
    effect: '+2% ticket gate per level',
  },
  {
    id: 'travel_package',
    name: 'Travel & Catering',
    level: 0,
    baseCost: 7_500,
    upgradeCostMultiplier: 2.35,
    requiredLeagueIndex: 2,
    maxLevelByLeagueIndex: [...FACILITY_MAX_LEVEL_BY_LEAGUE.travel_package],
    description: 'Keep the crew fed and on time so every town feels like a headline market.',
    effect: '+$750 show bonus per level',
  },
  {
    id: 'sponsor_lounge',
    name: 'Sponsor Lounge',
    level: 0,
    baseCost: 14_000,
    upgradeCostMultiplier: 2.5,
    requiredLeagueIndex: 3,
    maxLevelByLeagueIndex: [...FACILITY_MAX_LEVEL_BY_LEAGUE.sponsor_lounge],
    description: 'Corporate partners cut checks for access, signage, and soft drinks nobody drinks.',
    effect: '+$2,500 show bonus per level',
  },
];

export const MARKETING_CAMPAIGNS: MarketingCampaign[] = [
  {
    id: 'social',
    name: 'Social Media Blitz',
    cost: 1000,
    duration: 1,
    popularityBoost: 1,
  },
  {
    id: 'tv',
    name: 'Local TV Ad',
    cost: 4000,
    duration: 3,
    popularityBoost: 3,
  },
  {
    id: 'billboard',
    name: 'Highway Billboard',
    cost: 10000,
    duration: 5,
    popularityBoost: 8,
  },
];

export const FIGHTER_NAMES = [
  'The Crusher',
  'El Diablo',
  'Thunder Bolt',
  'Silver Shadow',
  'The Beast',
  'Golden Boy',
  'Iron Fist',
  'The Ghost',
  'Raging Bull',
  'Snake Eyes',
  'The Professor',
  'Wild Card',
  'Big Bad Wolf',
  'The King',
  'Ace of Spades',
  'Midnight Express',
  'Crimson Tide',
  'Steel Curtain',
  'Vice Grip',
  'Blackout',
  'Solar Flare',
  'Ice Pick',
  'Rust Belt',
  'Copperhead',
  'Diamond Dust',
  'Velvet Hammer',
  'Chrome Heart',
  'Neon Serpent',
  'Voltage',
  'Circuit Breaker',
  'Main Event Mick',
  'Hardway Harry',
  'Roughhouse Rex',
  'Slam Duncan',
  'Canvas King',
  'Ropeside Rico',
  'Turnbuckle Tony',
  'Apron Al',
  'Belltime Ben',
  'Spotlight Steve',
  'Grandstand Gary',
  'Cheapshot Charlie',
  'Clean Fight Carl',
  'Ironclad Ivan',
  'Tsunami Tom',
  'Avalanche Andy',
  'Wildfire Wyatt',
  'Crossface Chris',
  'Dragon Sleeper Dan',
  'Flying Elbow Eli',
  'Powerbomb Pete',
  'Suplex Sam',
  'Clothesline Clay',
  'Dropkick Derek',
  'Spear Spencer',
  'Lariat Logan',
  'Piledriver Paul',
  'Boston Crab Brett',
  'Figure Four Finn',
  'Sleeper Hold Seth',
  'Hammerlock Hank',
  'Full Nelson Ned',
  'Bear Hug Bear',
  'Gorilla Press Gus',
  'Military Press Miles',
  'Gutwrench Gary',
  'Fireman Carry Frank',
  'Backbreaker Blake',
  'Spinebuster Sid',
  'Jackknife Jake',
  'Razor\'s Edge Ray',
  'Chokeslam Chase',
  'Tombstone Tyler',
  'Flying Headscissor Hugo',
  'Moonsault Mason',
  'Shooting Star Shane',
  'Phoenix Splash Phil',
  'Frog Splash Freddie',
  '450 Splash Felix',
  'Corkscrew Cole',
  'Springboard Steve',
  'Top Rope Terry',
  'Suicide Dive Dean',
  'Tope Con Hilo Hector',
  'Plancha Pete',
  'Senton Bomb Sean',
  'Elbow Drop Eddie',
  'Leg Drop Larry',
  'Flying Forearm Fred',
  'European Uppercut Evan',
  'Discus Punch Duncan',
  'Spinning Heel Kick Kyle',
  'Roundhouse Ron',
  'Superkick Scott',
  'Enzuigiri Enzo',
  'Stomp Out Stan',
  'Ground And Pound Greg',
  'Chain Wrestling Chad',
  'Catch Point Casey',
  'Shoot Style Shawn',
  'Strong Style Steve',
  'King Of Kings Kyle',
  'Emperor Edge',
  'Baron Von Bruise',
  'Duke Of Danger',
  'Count Cryptkeeper',
  'Lord Lightning',
  'Sir Slamalot',
  'Lady Lariat',
  'Queen Of Pain',
  'Valkyrie Vega',
  'Amazon Annie',
  'She-Wolf Sierra',
  'Panther Princess',
  'Tiger Lily',
  'Cobra Kaiju',
  'Anaconda Ace',
  'Viper Vaughn',
  'Mamba Max',
  'Rattlesnake Rick',
  'Scorpion Sting',
  'Tarantula Ted',
  'Widowmaker Walt',
  'Reaper Rowan',
  'Grim Gallows',
  'Bone Collector',
  'Skull Crusher',
  'Spine Snapper',
  'Ribcage Rex',
  'Knuckle Sandwich',
  'Brass Knuckles Bob',
  'Bare Knuckle Bill',
  'Street Fight Steve',
  'No DQ Nick',
  'Cage Match Carl',
  'Ladder Match Luke',
  'Tables Match Tom',
  'TLC Terry',
  'Hardcore Hank',
  'Extreme Eddie',
  'Deathmatch Dave',
  'Barbed Wire Barry',
  'Thumbtack Tim',
  'Light Tube Larry',
  'Kendo Stick Ken',
  'Chair Shot Charlie',
  'Sledgehammer Sam',
  'Crowbar Carl',
  'Pipe Bomb Pete',
  'Chain Link Larry',
  'Handcuff Harry',
  'Duct Tape Dan',
  'Zip Tie Zack',
  'Blindfold Brad',
  'Iron Man Ivan',
  'Survivor Series Sid',
  'Royal Rumble Ron',
  'Money In The Bank Mitch',
  'Cash In Carl',
  'Contract Killer',
  'Hitman Harvey',
  'Assassin Ace',
  'Mercenary Mike',
  'Bounty Hunter Bo',
  'Wanted Man Walt',
  'Outlaw Owen',
  'Renegade Ray',
  'Desperado Dan',
  'Bandit Billy',
  'Highway Robber',
  'Train Robber Tony',
  'Bank Vault Vic',
  'Safe Cracker Sal',
  'Jewel Thief Jake',
  'Gold Rush Gus',
  'Silver Bullet Silas',
  'Platinum Pat',
  'Titanium Tim',
  'Carbon Fiber Carl',
  'Kevlar Kyle',
  'Bulletproof Bob',
  'Tank Top Tom',
  'Armored Al',
  'Fortress Frank',
  'Bunker Buster',
  'Siege Engine Steve',
  'Catapult Carl',
  'Ballista Bill',
  'Trebuchet Terry',
  'Cannonball Chris',
  'Howitzer Hank',
  'Mortar Mike',
  'Grenade Gary',
  'Flashbang Frank',
  'Smoke Bomb Steve',
  'Mirage Max',
  'Phantom Phil',
  'Specter Sid',
  'Wraith Walt',
  'Banshee Ben',
];

export const ALIGNMENTS = ['Face', 'Heel'] as const;
export const TRAITS = ['Technician', 'Brawler', 'High Flyer', 'Powerhouse'] as const;
