import { Fighter, Facility, MarketingCampaign, Venue } from './types';

export const INITIAL_MONEY = 0;
export const INITIAL_POPULARITY = 1;

export const VENUES: Venue[] = [
  {
    id: 'backyard',
    name: 'Backyard',
    cost: 0,
    multiplier: 1,
    minPopularity: 0,
    maxAudience: 75,
    baseTicketPrice: 10,
  },
  {
    id: 'gym',
    name: 'High School Gym',
    cost: 500,
    multiplier: 1.5,
    minPopularity: 5,
    maxAudience: 420,
    baseTicketPrice: 16,
  },
  {
    id: 'club',
    name: 'Nightclub',
    cost: 1500,
    multiplier: 2.5,
    minPopularity: 15,
    maxAudience: 1100,
    baseTicketPrice: 26,
  },
  {
    id: 'arena',
    name: 'City Arena',
    cost: 5000,
    multiplier: 5,
    minPopularity: 40,
    maxAudience: 5200,
    baseTicketPrice: 42,
  },
];

export const STARTING_FIGHTERS: Fighter[] = [
  {
    id: 'f1',
    name: 'The Iron Giant',
    stats: { strength: 28, charisma: 14, stamina: 20, skill: 16 },
    salary: 0,
    signingBonus: 0,
    popularity: 6,
    energy: 100,
    alignment: 'Heel',
    trait: 'Powerhouse',
    injuryDays: 0,
    recoveringFromInjury: false,
    image: '/wrestler.png',
  },
  {
    id: 'f2',
    name: 'Neon Ninja',
    stats: { strength: 14, charisma: 22, stamina: 22, skill: 26 },
    salary: 0,
    signingBonus: 0,
    popularity: 8,
    energy: 100,
    alignment: 'Face',
    trait: 'High Flyer',
    injuryDays: 0,
    recoveringFromInjury: false,
    image: '/wrestler.png',
  },
  {
    id: 'f3',
    name: 'Bulk Hogan',
    stats: { strength: 26, charisma: 20, stamina: 16, skill: 14 },
    salary: 0,
    signingBonus: 0,
    popularity: 10,
    energy: 100,
    alignment: 'Face',
    trait: 'Brawler',
    injuryDays: 0,
    recoveringFromInjury: false,
    image: '/wrestler.png',
  },
];

export const AVAILABLE_FACILITIES: Facility[] = [
  {
    id: 'performance_center',
    name: 'Performance Center',
    level: 0,
    baseCost: 4200,
    description: 'Unlocks recruiting and adds one concurrent rookie training slot per level.',
    effect: '+1 recruit slot per level',
  },
];

export const MARKETING_CAMPAIGNS: MarketingCampaign[] = [
  {
    id: 'social',
    name: 'Social Media Blitz',
    cost: 1000,
    duration: 1,
    popularityBoost: 1,
  },
  {
    id: 'tv',
    name: 'Local TV Ad',
    cost: 4000,
    duration: 3,
    popularityBoost: 3,
  },
  {
    id: 'billboard',
    name: 'Highway Billboard',
    cost: 10000,
    duration: 5,
    popularityBoost: 8,
  },
];

export const FIGHTER_NAMES = [
  'The Crusher',
  'El Diablo',
  'Thunder Bolt',
  'Silver Shadow',
  'The Beast',
  'Golden Boy',
  'Iron Fist',
  'The Ghost',
  'Raging Bull',
  'Snake Eyes',
  'The Professor',
  'Wild Card',
  'Big Bad Wolf',
  'The King',
  'Ace of Spades',
  'Midnight Express',
  'Crimson Tide',
  'Steel Curtain',
  'Vice Grip',
  'Blackout',
  'Solar Flare',
  'Ice Pick',
  'Rust Belt',
  'Copperhead',
  'Diamond Dust',
  'Velvet Hammer',
  'Chrome Heart',
  'Neon Serpent',
  'Voltage',
  'Circuit Breaker',
  'Main Event Mick',
  'Hardway Harry',
  'Roughhouse Rex',
  'Slam Duncan',
  'Canvas King',
  'Ropeside Rico',
  'Turnbuckle Tony',
  'Apron Al',
  'Belltime Ben',
  'Spotlight Steve',
  'Grandstand Gary',
  'Cheapshot Charlie',
  'Clean Fight Carl',
  'Ironclad Ivan',
  'Tsunami Tom',
  'Avalanche Andy',
  'Wildfire Wyatt',
  'Crossface Chris',
  'Dragon Sleeper Dan',
  'Flying Elbow Eli',
  'Powerbomb Pete',
  'Suplex Sam',
  'Clothesline Clay',
  'Dropkick Derek',
  'Spear Spencer',
  'Lariat Logan',
  'Piledriver Paul',
  'Boston Crab Brett',
  'Figure Four Finn',
  'Sleeper Hold Seth',
  'Hammerlock Hank',
  'Full Nelson Ned',
  'Bear Hug Bear',
  'Gorilla Press Gus',
  'Military Press Miles',
  'Gutwrench Gary',
  'Fireman Carry Frank',
  'Backbreaker Blake',
  'Spinebuster Sid',
  'Jackknife Jake',
  'Razor\'s Edge Ray',
  'Chokeslam Chase',
  'Tombstone Tyler',
  'Flying Headscissor Hugo',
  'Moonsault Mason',
  'Shooting Star Shane',
  'Phoenix Splash Phil',
  'Frog Splash Freddie',
  '450 Splash Felix',
  'Corkscrew Cole',
  'Springboard Steve',
  'Top Rope Terry',
  'Suicide Dive Dean',
  'Tope Con Hilo Hector',
  'Plancha Pete',
  'Senton Bomb Sean',
  'Elbow Drop Eddie',
  'Leg Drop Larry',
  'Flying Forearm Fred',
  'European Uppercut Evan',
  'Discus Punch Duncan',
  'Spinning Heel Kick Kyle',
  'Roundhouse Ron',
  'Superkick Scott',
  'Enzuigiri Enzo',
  'Stomp Out Stan',
  'Ground And Pound Greg',
  'Chain Wrestling Chad',
  'Catch Point Casey',
  'Shoot Style Shawn',
  'Strong Style Steve',
  'King Of Kings Kyle',
  'Emperor Edge',
  'Baron Von Bruise',
  'Duke Of Danger',
  'Count Cryptkeeper',
  'Lord Lightning',
  'Sir Slamalot',
  'Lady Lariat',
  'Queen Of Pain',
  'Valkyrie Vega',
  'Amazon Annie',
  'She-Wolf Sierra',
  'Panther Princess',
  'Tiger Lily',
  'Cobra Kaiju',
  'Anaconda Ace',
  'Viper Vaughn',
  'Mamba Max',
  'Rattlesnake Rick',
  'Scorpion Sting',
  'Tarantula Ted',
  'Widowmaker Walt',
  'Reaper Rowan',
  'Grim Gallows',
  'Bone Collector',
  'Skull Crusher',
  'Spine Snapper',
  'Ribcage Rex',
  'Knuckle Sandwich',
  'Brass Knuckles Bob',
  'Bare Knuckle Bill',
  'Street Fight Steve',
  'No DQ Nick',
  'Cage Match Carl',
  'Ladder Match Luke',
  'Tables Match Tom',
  'TLC Terry',
  'Hardcore Hank',
  'Extreme Eddie',
  'Deathmatch Dave',
  'Barbed Wire Barry',
  'Thumbtack Tim',
  'Light Tube Larry',
  'Kendo Stick Ken',
  'Chair Shot Charlie',
  'Sledgehammer Sam',
  'Crowbar Carl',
  'Pipe Bomb Pete',
  'Chain Link Larry',
  'Handcuff Harry',
  'Duct Tape Dan',
  'Zip Tie Zack',
  'Blindfold Brad',
  'Iron Man Ivan',
  'Survivor Series Sid',
  'Royal Rumble Ron',
  'Money In The Bank Mitch',
  'Cash In Carl',
  'Contract Killer',
  'Hitman Harvey',
  'Assassin Ace',
  'Mercenary Mike',
  'Bounty Hunter Bo',
  'Wanted Man Walt',
  'Outlaw Owen',
  'Renegade Ray',
  'Desperado Dan',
  'Bandit Billy',
  'Highway Robber',
  'Train Robber Tony',
  'Bank Vault Vic',
  'Safe Cracker Sal',
  'Jewel Thief Jake',
  'Gold Rush Gus',
  'Silver Bullet Silas',
  'Platinum Pat',
  'Titanium Tim',
  'Carbon Fiber Carl',
  'Kevlar Kyle',
  'Bulletproof Bob',
  'Tank Top Tom',
  'Armored Al',
  'Fortress Frank',
  'Bunker Buster',
  'Siege Engine Steve',
  'Catapult Carl',
  'Ballista Bill',
  'Trebuchet Terry',
  'Cannonball Chris',
  'Howitzer Hank',
  'Mortar Mike',
  'Grenade Gary',
  'Flashbang Frank',
  'Smoke Bomb Steve',
  'Mirage Max',
  'Phantom Phil',
  'Specter Sid',
  'Wraith Walt',
  'Banshee Ben',
];

export const ALIGNMENTS = ['Face', 'Heel'] as const;
export const TRAITS = ['Technician', 'Brawler', 'High Flyer', 'Powerhouse'] as const;
